// fernando-gomez/lectures/typescript-demo/tour-of-heroes/src/app/heroes/heroes.component.ts
import { Component, OnInit } from '@angular/core';
import { Hero } from '../hero';

@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.css']
})
export class HeroesComponent implements OnInit {

  heroes: Hero[] = [
    {id: 11, name: 'Dr Nice'},
    {id: 12, name: 'Narco'},
    {id: 13, name: 'Bombasto'},
    {id: 14, name: 'Celeritas'},
    {id: 15, name: 'Magneta'},
    {id: 16, name: 'RubberMan'},
    {id: 17, name: 'Dynama'},
    {id: 18, name: 'Dr IQ'},
    {id: 19, name: 'Magma'},
    {id: 20, name: 'Tornado'},
    {id: 21, name: 'Lefty'},
  ];

  selectedHero!: Hero;

  constructor() { }

  ngOnInit(): void {
  }

}

<ul>
    <li *ngFor='let hero of heroes' 
    (click)='selectedHero = hero'
    [class.selected] = 'hero === selectedHero'
    >
        <span class='badge'>{{ hero.id }}</span> {{ hero.name }}
    </li>
</ul>

<app-hero-detail [hero]='selectedHero'></app-hero-detail>

// fernando-gomez/lectures/toh-redux/src/Components/Heroes/index.jsx
import React from 'react';

const Heroes = () =>
//   const HEROES = [
//     { id: 11, name: 'Dr Nice' },
//     { id: 12, name: 'Narco' },
//     { id: 13, name: 'Bombasto' },
//     { id: 14, name: 'Celeritas' },
//     { id: 15, name: 'Magneta' },
//     { id: 16, name: 'RubberMan' },
//     { id: 17, name: 'Dynama' },
//     { id: 18, name: 'Dr IQ' },
//     { id: 19, name: 'Magma' },
//     { id: 20, name: 'Tornado' },
//   ];

  (
    <div />
  );
export default Heroes;
