// hosni-marco/challenge/toh-angular/angular-tour-of-heroes/src/app/heroes/heroes.component.ts
import { Component, OnInit } from '@angular/core';
import { Hero } from '../hero';

@Component({
  selector: 'app-heroes',
  templateUrl: './heroes.component.html',
  styleUrls: ['./heroes.component.css'],
})
export class HeroesComponent implements OnInit {
  hero: Hero = {
    id: 1,
    name: 'Windstorm'
  };
  constructor() { }

  ngOnInit(): void {

  }

}

<h2>My Heroes</h2>



<div>
  <label for="new-hero">Hero name: </label>
  <input id="new-hero" #heroName />

  <!-- (click) passes input value to add() and then clears the input -->
  <button class="add-button" (click)="add(heroName.value); heroName.value=''">
    Add hero
  </button>
</div>

<ul class="heroes">
  <li *ngFor="let hero of heroes">
    <a routerLink="/detail/{{hero.id}}">
      <span class="badge">{{hero.id}}</span> {{hero.name}}
    </a>
    <button class="delete" title="delete hero"
      (click)="delete(hero)">x</button>
  </li>
</ul>

// alfredo-zimperz/lectures/tour-of-heroes-redux/src/components/Heroes/index.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import HEROES from '../../constants/heroes.mock';
import './heroes.css';

const Heroes = () => (
  <>
    <h2>My Heroes</h2>

    <div>
      <label htmlFor="new-hero" id="new-hero">
        Hero name:
        <input htmlFor="new-hero" />
      </label>
      <button className="add-button" type="button">
        Add hero
      </button>
    </div>

    <ul className="heroes">
      {HEROES.map((hero) => (
        <li key={hero.id}>
          <Link to={`/heroes/${hero.id}`}>
            <span className="badge">{hero.id}</span>
            {' '}
            {hero.name}
          </Link>
          <button
            className="delete"
            title="delete hero"
            type="button"
          >
            x
          </button>
        </li>
      ))}

    </ul>
  </>
);

export default Heroes;
