// cristian-bars/lectures/react-redux/toh-redux/src/componentes/Dashboard/index.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import './Dashboard.css';
import HEROES from '../Constants/Heroes.mock';

function Dashboard() {
  return (
    <>
      <h2>Top Heroes</h2>

      <div className="heroes-menu">
        {HEROES.slice(1, 5).map((heroe) => <Link to={`/detail/${heroe.id}`}>{heroe.name}</Link>)}
      </div>
    </>
  );
}
export default Dashboard;

// gilbe-cao/tour-of-heroes/src/app/components/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { HEROES } from 'src/app/constants/heroes.mock';


@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  heroes = HEROES.slice(1, 5);
}

<h2>Top Heroes</h2>
<div class="heroes-menu">
  <a *ngFor="let hero of heroes"
      [routerLink]="['/detail',hero._id]">
      {{hero.name}}
  </a>
</div>
